# Generated by Django 3.2.25 on 2024-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
